name: e2e example
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn build

      - name: Restore GoogleService info
        env:
          GOOGLE_SERVICE: ${{ secrets.GOOGLE_SERVICE_JSON }}
          GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          echo $GOOGLE_SERVICE | base64 --decode > packages/example/android/app/google-services.json
          echo $GOOGLE_SERVICE_INFO_PLIST | base64 --decode > packages/example/ios/App/GoogleService-Info.plist

      - name: Run appium server
        run: mkdir -p logs && yarn e2e:appium > logs/appium.log &

      - name: Run Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          profile: pixel_xl
          avd-name: Pixel_XL_API_30
          working_directory: packages/example/android

      - name: Build archives for Emulators
        run: yarn e2e:prepare > logs/build.log
        continue-on-error: true

      - name: Run e2e tests
        run: yarn e2e:run
        continue-on-error: true

      - name: Upload logs
        uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: logs
          path: logs
      - name: Upload screenshots
        uses: actions/upload-artifact@v1
        continue-on-error: true
        with:
          name: screenshots
          path: packages/example/protractor/screenshots
